# Generated by Django 5.2.4 on 2025-08-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_phone'),
        ('api', '0003_alter_userprofile_phone_unique'),
    ]

    operations = [
    ]
